#!/usr/bin/bash

python run_summarization.py \
	--model_name_or_path Bart-Pubmed_Summarizer \
	--do_eval \
	--dataset_name ccdv/pubmed-summarization \
	--summary_column abstract \
	--text_column article \
	--per_device_train_batch_size=3 \
	--per_device_eval_batch_size=3 \
	--predict_with_generate \
	--save_total_limit 10 \
	--num_train_epochs 4 \
	--output_dir ./Bart-Pubmed_eval
